# Generated by Django 3.0.5 on 2023-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.BigIntegerField(max_length=10)),
                ('cc', models.BigIntegerField(max_length=20)),
                ('exp', models.DateField()),
                ('cvv', models.IntegerField(max_length=5)),
            ],
        ),
    ]
