# Generated by Django 3.0.5 on 2023-09-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
