# Generated by Django 3.0.5 on 2023-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_connect_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='event',
            field=models.BooleanField(),
        ),
    ]
