# Generated by Django 3.0.5 on 2023-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20230914_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='event',
            field=models.CharField(max_length=50),
        ),
    ]
